config/routes.rb
Rails.application.routes.draw do
  resources :roasts do
    get "/import", on: :collection, to: "roasts#import_form"
    post "/import", on: :collection, to: "roasts#import"
    get "/import/:job_id", to: "roasts#import_wait", on: :collection, as: :import_wait
  end

  # Auth resources
  get "/login", to: "sessions#new", as: :new_session
  post "/login", to: "sessions#create", as: :session
  resources :register, only: %i[ new create ]
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "roasts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/roast.rb
class Roast < ApplicationRecord
  belongs_to :user

  enum :status, [ :resting, :grinding, :done ]
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :roasts

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id])
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_url
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end


    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_url, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_url, notice: "Password has been reset."
    else
      redirect_to edit_password_url(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_url, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  allow_unauthenticated_access

  def create
    @user = User.new(user_params)
    if @user.save
      start_new_session_for @user
      redirect_to roasts_path, notice: "Registration successful."
    else
      render :new
    end
  end

  private

  def user_params
    params.permit(:email_address, :password)
  end
end

app/controllers/roasts_controller.rb
require "securerandom"
require "uri"

class RoastsController < ApplicationController
  def index
    @roasts_grinding = Current.user.roasts.grinding.all
    @roasts_resting = Current.user.roasts.resting.all
  end

  def import_form
  end

  def import
    url = params[:url]
    job_id = SecureRandom.uuid

    if !valid_url?(url)
      flash[:error] = "Invalid URL"
      redirect_to import_roasts_path
      return
    end

    ExtractRoastFromUrlJob.perform_later(job_id, url, Current.user.id)

    redirect_to import_wait_roasts_path(job_id: job_id)
  end

  def import_wait
  end

  private

  def valid_url?(url)
    url =~ URI.regexp
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_url, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/roasts_helper.rb
module RoastsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Coffee Collector" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-10 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/register/new.html.erb
<div class="min-w-full items-center">
  <div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
    <div class="sm:mx-auto sm:w-full sm:max-w-sm">
      <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Start Collecting!</h2>
    </div>
    
    <div class="mt-5 flex justify-center sm:mx-auto sm:w-full sm:max-w-sm">
      <%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>
      
      <%= form_with class: "space-y-6", url: register_index_path do |form| %>
        <div>
          <%= form.label :email_address, "Email Address", class: "block text-sm font-medium leading-6 text-gray-900" %>
          <div class="mt-2">
            <%= form.email_field :email_address, required: true, autofocus: true, autocomplete: "username", placeholder: "Enter your email address", value: params[:email_address] %><br>
          </div>
        </div>
        
        <div>
          <%= form.label :password, "Password", class: "block text-sm font-medium leading-6 text-gray-900" %>
          <div class="mt-2">
            <%= form.password_field :password, required: true, autocomplete: "password", placeholder: "Password", value: params[:password] %><br />
          </div>
        </div>
        <%= form.submit "Register", class: "flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
      <% end %>
    </div>
  </div>
</div>

app/views/roasts/import_form.html.erb
<%= form_with url: import_roasts_path do |form| %>
<div class="grid grid-cols-1 gap-8">
  <div>
    <span class="text-lg font-light leading-relaxed mt-0 mb-4">
      Quickly import the details of your roast directly from the store of your
      favorite roaster. Paste the URL to the listing below, and we'll do the
      rest!
    </span>
  </div>
  <div>
    <%= form.text_field :url, required: true, autofocus: true, placeholder: "URL", class: "px-3 py-4 placeholder-blueGray-300 text-blueGray-600 relative bg-white rounded text-base border-0 shadow outline-none focus:outline-none focus:ring w-full", value: params[:email_address] %><br>
    <%= tag.span(flash[:error], class: "flex items-center font-medium tracking-wide text-red-500 text-xs mt-1 ml-1") if flash[:error] %>
  </div>
  <div>
    <%= form.submit "Import Roast", class: "bg-blue-500 text-white active:bg-blue-600 font-bold uppercase text-xs px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1" %>
    <a href="/roasts" class="bg-red-500 text-white active:bg-red-600 font-bold uppercase text-xs px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1">
      Cancel
    </a>
  </div>
</div>
<% end %>

app/views/roasts/import_wait.html.erb
<div class="container mx-auto max-w-3xl bg-white p-8 mb-8 rounded-lg shadow-lg">
  <!-- Coffee Title -->
  <div class="grid grid-cols-2 sm:grid-cols-4 justify-between mb-6">
    <div class="col-span-2">
      <h1 class="text-3xl font-bold mb-4">Ethiopian Yergacheffe</h1>
    </div>
    <div class="col-span-2 flex sm:justify-end">
      <div>
        <a href="/roasts" class="bg-red-500 text-white active:bg-red-600 font-bold uppercase text-xs px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1">
          Cancel
        </a>
        <button class="bg-blue-500 text-white active:bg-blue-600 font-bold uppercase text-xs px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1">
          Confirm
        </button>
      </div>
    </div>
  </div>

  <!-- Hero Image Section -->
  <div class="bg-gray-200 h-64 flex items-center justify-center rounded-lg mb-6">
      <p class="text-xl text-gray-500">Some kind of hero photo image</p>
  </div>

  <!-- Coffee Description -->
  <p class="text-gray-700 mb-4">
      This is where the notes about the coffee go. We describe it here, maybe info about the grower, the roaster, and the roast process.
  </p>
  <p class="text-gray-600 font-semibold mb-8">Fruity, aromatic, abundant</p>

  <!-- Maps Section -->
  <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
      <!-- Elevation Map -->
      <div class="bg-gray-100 h-40 flex flex-col items-center justify-center rounded-lg">
          <p class="text-gray-600 mb-2">Elevation map</p>
          <p class="text-gray-700 font-semibold">1500ft</p>
      </div>

      <!-- Regional Map -->
      <div class="bg-gray-100 h-40 flex items-center justify-center rounded-lg">
          <p class="text-gray-500">Regional map image goes here</p>
      </div>
  </div>
</div>

app/views/roasts/index.html.erb
<div class="container mx-auto p-8">
  <!-- Title -->
  <h1 class="text-4xl font-bold mb-8">My Collection</h1>

  <div class="grid grid-cols-2 gap-8">
    <!-- Now Grinding Section -->
    <div class="bg-white p-6 shadow-lg rounded-lg">
      <h2 class="text-2xl font-semibold mb-4">Now Grinding</h2>
      <ul>
        <% if @roasts_grinding.empty? %>
        <li class="flex items-center mb-4">
            <span>Nothing on deck. Move beans from Resting to Grinding to begin.</span>
        </li>
        <% end %>

        <% @roasts_grinding.each do |roast| %>
        <li class="flex items-center mb-4">
          <div class="w-12 h-12 bg-gray-200 rounded-md mr-4"></div>
          <span><%= roast.name %></span>
        </li>
        <% end %>
      </ul>
    </div>

    <!-- Resting Section -->
    <div class="bg-white p-6 shadow-lg rounded-lg">
      <div class="flex justify-between items-center mb-4">
        <h2 class="text-2xl font-semibold">Resting</h2>
        <a
          href="/roasts/import"
          class="w-8 h-8 bg-gray-300 rounded-full flex items-center justify-center text-xl"
        >
          +
        </a>
      </div>
      <ul>
        <% if @roasts_resting.empty? %>
        <li class="flex items-center mb-4">
            <span>Nothing on deck. Add some new beans?</span>
        </li>
        <% end %>

        <% @roasts_resting.each do |roast| %>
        <li class="flex items-center mb-4">
          <div class="w-12 h-12 bg-gray-200 rounded-md mr-4"></div>
          <span><%= roast.name %></span>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>